--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-27 00:19:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4929 (class 1262 OID 16539)
-- Name: aluno_online_casa; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE aluno_online_casa WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'pt-BR';


ALTER DATABASE aluno_online_casa OWNER TO postgres;

\connect aluno_online_casa

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16541)
-- Name: aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aluno (
    id bigint NOT NULL,
    cpf character varying(255),
    email character varying(255),
    nome character varying(255)
);


ALTER TABLE public.aluno OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16540)
-- Name: aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aluno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16548)
-- Name: aluno_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.aluno_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.aluno_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16590)
-- Name: disciplina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disciplina (
    id bigint NOT NULL,
    carga_horaria integer,
    nome character varying(255),
    professor_id bigint
);


ALTER TABLE public.disciplina OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16589)
-- Name: disciplina_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disciplina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16632)
-- Name: matricula_aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matricula_aluno (
    id bigint NOT NULL,
    nota1 double precision,
    nota2 double precision,
    status character varying(255),
    aluno_id bigint,
    disciplina_id bigint,
    CONSTRAINT matricula_aluno_status_check CHECK (((status)::text = ANY ((ARRAY['MATRICULADO'::character varying, 'APROVADO'::character varying, 'REPROVADO'::character varying, 'TRANCADO'::character varying])::text[])))
);


ALTER TABLE public.matricula_aluno OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16631)
-- Name: matricula_aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matricula_aluno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matricula_aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16562)
-- Name: professor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.professor (
    id bigint NOT NULL,
    cpf character varying(255),
    email character varying(255),
    nome character varying(255)
);


ALTER TABLE public.professor OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16561)
-- Name: professor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.professor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4916 (class 0 OID 16541)
-- Dependencies: 218
-- Data for Name: aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.aluno VALUES (4, '222.222.222-22', 'samu@gmail.com', 'samu');
INSERT INTO public.aluno VALUES (5, '444.444.444-44', 'oi@gmail.com', 'oi');
INSERT INTO public.aluno VALUES (6, '444.444.444-44', 'oi@gmail.com', 'oi');
INSERT INTO public.aluno VALUES (7, '444.444.444-44', 'oi@gmail.com', 'oisdasa');
INSERT INTO public.aluno VALUES (8, 'string', 'string', 'samu');


--
-- TOC entry 4921 (class 0 OID 16590)
-- Dependencies: 223
-- Data for Name: disciplina; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.disciplina VALUES (2, 60, 'disciplinaAtualizada', 2);
INSERT INTO public.disciplina VALUES (4, 60, 'disciplinaneto', 4);
INSERT INTO public.disciplina VALUES (3, 80, 'atualizadaDisciplinaMailson', 3);


--
-- TOC entry 4923 (class 0 OID 16632)
-- Dependencies: 225
-- Data for Name: matricula_aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.matricula_aluno VALUES (1, 0, 0, 'MATRICULADO', 4, 2);
INSERT INTO public.matricula_aluno VALUES (3, 0, 0, 'TRANCADO', 4, 2);
INSERT INTO public.matricula_aluno VALUES (5, 0, 0, 'TRANCADO', 8, 2);
INSERT INTO public.matricula_aluno VALUES (8, NULL, NULL, 'MATRICULADO', 7, 2);
INSERT INTO public.matricula_aluno VALUES (6, 0, 0, 'TRANCADO', 8, 2);
INSERT INTO public.matricula_aluno VALUES (7, 7, 9, 'APROVADO', 7, 2);


--
-- TOC entry 4919 (class 0 OID 16562)
-- Dependencies: 221
-- Data for Name: professor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.professor VALUES (2, '010.010.010-01', 'teste@gmail.com', 'teste');
INSERT INTO public.professor VALUES (3, '020.020.020-20', 'mailson@gmail.com', 'mailson');
INSERT INTO public.professor VALUES (4, '030.030.030-30', 'neto@gmail.com', 'neto');
INSERT INTO public.professor VALUES (6, '040.040.040-44', 'professoratt@gmail.com', 'professoratt');


--
-- TOC entry 4931 (class 0 OID 0)
-- Dependencies: 217
-- Name: aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aluno_id_seq', 8, true);


--
-- TOC entry 4932 (class 0 OID 0)
-- Dependencies: 219
-- Name: aluno_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aluno_seq', 1, false);


--
-- TOC entry 4933 (class 0 OID 0)
-- Dependencies: 222
-- Name: disciplina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disciplina_id_seq', 5, true);


--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 224
-- Name: matricula_aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matricula_aluno_id_seq', 8, true);


--
-- TOC entry 4935 (class 0 OID 0)
-- Dependencies: 220
-- Name: professor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.professor_id_seq', 6, true);


--
-- TOC entry 4760 (class 2606 OID 16547)
-- Name: aluno aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_pkey PRIMARY KEY (id);


--
-- TOC entry 4764 (class 2606 OID 16594)
-- Name: disciplina disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_pkey PRIMARY KEY (id);


--
-- TOC entry 4766 (class 2606 OID 16637)
-- Name: matricula_aluno matricula_aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT matricula_aluno_pkey PRIMARY KEY (id);


--
-- TOC entry 4762 (class 2606 OID 16568)
-- Name: professor professor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT professor_pkey PRIMARY KEY (id);


--
-- TOC entry 4768 (class 2606 OID 16643)
-- Name: matricula_aluno fk4mtt3iew11xcs5i7tshj7la9q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT fk4mtt3iew11xcs5i7tshj7la9q FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(id);


--
-- TOC entry 4769 (class 2606 OID 16638)
-- Name: matricula_aluno fkn1iea49e3kxfecd5e27i7lvak; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT fkn1iea49e3kxfecd5e27i7lvak FOREIGN KEY (aluno_id) REFERENCES public.aluno(id);


--
-- TOC entry 4767 (class 2606 OID 16595)
-- Name: disciplina fkoqie7f1kx32b1atco9fpgxd7g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT fkoqie7f1kx32b1atco9fpgxd7g FOREIGN KEY (professor_id) REFERENCES public.professor(id);


-- Completed on 2025-05-27 00:19:11

--
-- PostgreSQL database dump complete
--

